# -*- coding: utf-8 -*-
"""HW2_hash_practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNJxLbHquYsQ1W5vNrb-Hgz8xg2xfHBN
"""

import matplotlib.pyplot as plt

# 使用 dictionary (hash) 記錄每個單字的出現次數
word_count = {}

with open('hw2_data.txt', 'r') as file:
    for line in file:
        word = line.strip()
        if word:
            if word in word_count:
                word_count[word] += 1
            else:
                word_count[word] = 1

# 印出基本統計
print(f"不重複的英文字總數: {len(word_count)}")
print("每個英文字出現次數:")
for word, count in word_count.items():
    print(f"{word}: {count}")

# 排序並準備畫圖資料
sorted_items = sorted(word_count.items(), key=lambda item: item[1], reverse=True)
words = [item[0] for item in sorted_items]
counts = [item[1] for item in sorted_items]

# 畫圖
plt.figure(figsize=(10, 6))
bars = plt.bar(words, counts, color='#B57EDC')

# 加上每個長條上方的數字標籤（Y 軸數值）
for bar, count in zip(bars, counts):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, height + 1, str(count),
             ha='center', va='bottom', fontsize=8)

plt.xticks(rotation=45)
plt.xlabel('Words')
plt.ylabel('Frequency')
plt.title('Word Frequency from hw2_data.txt')
plt.tight_layout()
plt.show()